Repository LetsGetTechnical/elecretanta, pull requests merged in 2025-05, with the labels that each got.

#374 Lillian/275 eslint errors navlogo component
  .eslintignore
  components/NavLogo/NavLogo.tsx
Labels: point-5

#359 Hadi/209-add-unit-tests-for-select-component
  app/onboarding/page.tsx
  components/Select/Select.test.tsx
  components/Select/Select.tsx
  components/Select/SelectContent.test.tsx
  components/Select/SelectContent.tsx
  components/Select/SelectItem.test.tsx
  components/Select/SelectItem.tsx
  components/Select/SelectLabel.test.tsx
  components/Select/SelectLabel.tsx
  components/Select/SelectScrollDownButton.tsx
  components/Select/SelectScrollUpButton.tsx
  components/Select/SelectSeparator.test.tsx
  components/Select/SelectSeparator.tsx
  components/Select/SelectTrigger.test.tsx
  components/Select/SelectTrigger.tsx
  components/Select/index.ts
  components/Select/select.tsx
  package.json
  pnpm-lock.yaml
Labels: point-13

#368 test #181: add unit tests for Card component
  app/onboarding/page.tsx
  app/page.tsx
  components/Card/Card.test.tsx
  components/Card/Card.tsx
  components/Card/CardContent.test.tsx
  components/Card/CardContent.tsx
  components/Card/CardDescription.test.tsx
  components/Card/CardDescription.tsx
  components/Card/CardFooter.test.tsx
  components/Card/CardFooter.tsx
  components/Card/CardHeader.test.tsx
  components/Card/CardHeader.tsx
  components/Card/CardTitle.test.tsx
  components/Card/CardTitle.tsx
  components/Card/card.tsx
  components/CompletedExchangeCard/CompletedExchangeCard.tsx
  components/GiftDetailsView/GiftDetailsView.tsx
  components/GiftSuggestionCard/GiftSuggestionCard.tsx
  components/ImageSelector/ImageSelector.tsx
  components/InviteCard/InviteCard.tsx
  components/JourneyCard/JourneyCard.tsx
  components/LoadingSkeleton/LoadingSkeleton.tsx
  components/MembersList/MembersList.tsx
Labels: point-8
